name: Publish
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Package
        run: cargo package

      - name: Publish
        run: |
          cargo login ${{ secrets.TOKEN_CRATES_IO }}
          cargo publish
